version: '2'
volumes:
  resin-data:
services:
  celery:
    build: ./app
    depends_on:
      - redis
    volumes:
      - 'resin-data:/data'
    environment:
      CELERY: 1
    labels:
      io.balena.features.kernel-modules: '1'
      io.balena.features.firmware: '1'
      io.balena.features.sysfs: '1'
      io.balena.features.procfs: '1'
    devices:
      - "/dev/ttyAMA0:/dev/ttyAMA0"
    cap_add:
      - SYS_RAWIO
  gunicorn:
    build: ./app
    expose:
      - "80"
    depends_on:
      - redis
    volumes:
      - 'resin-data:/data'
    environment:
      GUNICORN: 1
  redis:
    build: ./redis
    volumes:
      - 'resin-data:/data'
