version: '3'
volumes:
  resin-data:
services:
  celery:
    build:
      context: ./app
      dockerfile: Dockerfile.x86
    depends_on:
      - redis
      - postgres
    restart: on-failure
    volumes:
      - './app/django:/usr/src/app'
      - 'resin-data:/data'
    environment:
      CELERY: 1
      DISABLE_ANALYTICS: 1
      USE_POSTGRES: 1
      POSTGRES_PASSWORD: randompassword
      POSTGRES_USER: sonar
      POSTGRES_DATABASE: sonar
    privileged: true
    network_mode: host
  gunicorn:
    build:
      context: ./app
      dockerfile: Dockerfile.x86
    restart: on-failure
    ports:
      - "80:80"
    depends_on:
      - redis
      - postgres
    volumes:
      - './app/django:/usr/src/app'
      - 'resin-data:/data'
    environment:
      GUNICORN: 1
      DEBUG: 1
      DEV_MODE: 1
      ALLOWED_HOSTS: localhost
      USE_POSTGRES: 1
      POSTGRES_PASSWORD: randompassword
      POSTGRES_USER: sonar
      POSTGRES_DATABASE: sonar
  redis:
    image: redis
    restart: on-failure
    ports:
      - "127.0.0.1:6379:6379"
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: sonar
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: randompassword
