version: '2'
volumes:
  resin-data:
services:
  frontend:
    build: ./app
    expose:
      - "80"
    depends_on:
      - redis
    volumes:
      - 'resin-data:/data'
  redis:
    build: ./redis
    volumes:
      - 'resin-data:/data'
