version: '2'
volumes:
  resin-data:
services:
  celery:
    build: ./app
    expose:
      - "80"
    depends_on:
      - redis
    volumes:
      - 'resin-data:/data'
    labels:
      io.balena.features.kernel-modules: '1'
      io.balena.features.firmware: '1'
      io.balena.features.sysfs: '1'
      io.balena.features.procfs: '1'
    build: ./redis
    volumes:
      - 'resin-data:/data'
