services:
  ble-scanner:
    build: .
    container_name: ble-scanner
    restart: unless-stopped
    volumes:
      - ble_data:/data
      - /var/run/dbus:/var/run/dbus  # Required for Bluetooth access
    devices:
      - /dev/bus/usb:/dev/bus/usb    # Required for Bluetooth hardware access
    environment:
      - TZ=UTC
    cap_add:
      - NET_ADMIN
      - NET_RAW
    privileged: true  # Required for Bluetooth access

volumes:
  ble_data:
    driver: local