version: '2'
volumes:
  resin-data:
services:
  celery:
    build: ./app
    depends_on:
      - redis
    volumes:
      - 'resin-data:/data'
    environment:
      CELERY: 1
    privileged: true
    labels:
      io.balena.features.dbus: "1"
  gunicorn:
    build: ./app
    ports:
      - "80:80"
    depends_on:
      - redis
    volumes:
      - 'resin-data:/data'
    environment:
      GUNICORN: 1
  redis:
    build: ./redis
    volumes:
      - 'resin-data:/data'
